# Generated by Django 5.1.1 on 2024-09-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='class_type',
            field=models.CharField(choices=[('EC', 'Economy'), ('BS', 'Business'), ('FC', 'First Class')], default='EC', max_length=20),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=8),
        ),
    ]
